
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ""
    autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
    autoupdate_schedule: monthly
    skip: []
    submodules: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=10000"]
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: ["--autofix", "--no-sort-keys",  "--indent", "4"]
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
        files: \.sh$
    -   id: detect-private-key
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
    -   id: markdownlint
        args: [--fix]
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.28
    hooks:
    -   id: uv-lock
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
    -   id: actionlint
-   repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
    -   id: typos
        args: ["--force-exclude"]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.12.1
    hooks:
    -   id: commitizen
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
